// Each question stores the correct choice first. The API rotates the displayed
// choices and checks answers on the server; answer keys are never sent early.
const L=(title,minutes,slides,questions)=>({title,minutes,slides,questions});
export const lessons=[
L('Candles: the four prices',4,[
 ['A candle is a short price story','Every candle records the open, high, low and close for one period. The body runs between the open and close; the thin wicks show how far price travelled beyond that body.','bull'],
 ['Read the bearish version','A bearish candle closes below its open. Its open is at the top of the red body, and its close is at the bottom. The upper and lower wick still mark the high and low.','bear'],
 ['Use the whole candle','The same shape can mean different things in a trend or range. Read its position and neighbouring candles before forming an idea.','both']],
 [
 ['What does OHLC stand for?','Open, high, low, close','Order, height, limit, close','Open, hold, low, chart'],
 ['What connects the open and close?','The body','The upper wick','The time axis'],
 ['What marks the highest price?','The top of the upper wick','The top of every body','The previous close'],
 ['Where is the open on a bearish body?','At the top','At the bottom','At the wick tip'],
 ['Where is the close on a bullish body?','At the top','At the bottom','At the low'],
 ['What does the lower wick reach?','The period low','The previous open','The next close'],
 ['Can a candle lack a visible upper wick?','Yes, if the high is at the body top','No, every candle has both wicks','Only on a daily chart'],
 ['What determines a candle’s period?','The chart timeframe','The body height','The candle colour'],
 ['Does a green candle prove the next one rises?','No, it only describes its own period','Yes, green predicts green','Only if it has no wick'],
 ['What should accompany a candle reading?','Its surrounding chart context','Only its colour','The future candles']]),
L('Bearish candles up close',4,[
 ['Open above, close below','A red candle represents a period that ended below where it began. The body’s height shows the net decline, not every trade along the way.','bear'],
 ['Wicks reveal failed travel','A long lower wick means price fell below the close before recovering. A long upper wick means price rose above the open before falling. Neither guarantees the next candle.','bear'],
 ['Context changes the message','A bearish candle after a long rise can be a pause; several declining swings give it different context. Look for structure before attaching a story.','both']],
 [
 ['A bearish candle closes where?','Below its open','Above its open','Exactly at its high'],['The top of a red body is usually the…','Open','Close','Low'],['The bottom of a red body is the…','Close','High','Open'],['A long red body shows…','A large open-to-close fall','High volume for certain','A guaranteed downtrend'],['A long lower wick on a red candle shows…','Price recovered from a lower point','Price never went below the close','The next candle must be green'],['Can a red candle appear in an uptrend?','Yes','No','Only on weekly charts'],['Does a red candle show every intraperiod move?','No, it summarises four prices','Yes, the body traces all trades','Only when no wick appears'],['What does a missing lower wick suggest?','The close may equal the low','There was no opening price','The high was not recorded'],['Is every bearish candle a sell signal?','No','Yes','Only a large one'],['What helps interpret repeated red candles?','Swing structure and nearby levels','Colour alone','The candle number']]),
L('Bodies, wicks and pressure',4,[
 ['Compare body size','A long body indicates a large difference between open and close. Relative size matters: compare it with recent candles on the same chart and timeframe.','both'],
 ['Read rejection carefully','A long wick records movement that did not hold through the close. It may signal hesitation or response at a level, but follow-through needs separate evidence.','bear'],
 ['Small bodies show balance','A small body means the open and close were close together. It can appear during a pause, tug-of-war or transition; context decides which interpretation is useful.','both']],
 [
 ['A large body measures…','Open-to-close distance','Trading volume','Time until the next candle'],['A long upper wick shows…','Price visited a higher level then retreated','Price must fall next','No trades occurred near the high'],['A small body means…','Open and close are near each other','There was no volatility','The market is closed'],['Why compare recent candles?','To judge relative size','To predict an exact target','To remove the need for risk limits'],['Can a small body have long wicks?','Yes','No','Only on one-hour charts'],['Does a wick prove a reversal?','No','Yes','Only if coloured red'],['What does a long lower wick show?','Price traded lower and returned','Price never fell','The close is always the high'],['Which part marks the whole traded range?','High-to-low including wicks','The body alone','The close alone'],['What might a tiny body after a fast move suggest?','A pause or indecision','A guaranteed turn','A missing price'],['What best confirms a wick interpretation?','Subsequent price action and context','Wick colour alone','A larger font on the chart']]),
L('Timeframes and scale',4,[
 ['One market, many views','Each candle covers the chart’s selected period. A 15-minute candle and a daily candle summarise different amounts of activity, so patterns should be interpreted in their own context.','both'],
 ['Zoom out, then in','A short chart can show a rise inside a longer downtrend. Check a broader timeframe to see whether a local move agrees with or opposes larger structure.','both'],
 ['Keep comparisons fair','Compare candles from the same timeframe and scale. A large candle on a quiet chart may not be large on another; avoid assuming equal meaning from equal pixel height.','both']],
 [
 ['A 15-minute candle covers…','15 minutes of price action','15 trades','15 price units'],['A daily candle covers…','One trading day or session','One hour','One month'],['Can a short rise exist inside a longer decline?','Yes','No','Only in synthetic data'],['Why check a broader timeframe?','To understand larger structure','To guarantee the next move','To remove all uncertainty'],['What can chart zoom change?','How dramatic a move looks','The recorded OHLC','The market’s actual orders'],['Should body sizes across different timeframes be compared directly?','Usually no','Always yes','Only if both are green'],['What is a timeframe?','The period represented by each candle','The current price','The number of traders'],['Does a 1-minute pattern override daily structure automatically?','No','Yes','Only on Fridays'],['What remains useful across timeframes?','Open, high, low and close','A guaranteed signal','The exact same volatility'],['What prevents misleading visual comparisons?','Checking timeframe and scale','Ignoring the axis','Looking only at colour']]),
L('Swing highs and lows',5,[
 ['Find the turning points','A swing high is a local peak followed by a pullback. A swing low is a local trough followed by a rise. You recognise them by comparing neighbouring prices, not by isolating one candle.','both'],
 ['Track the sequence','Higher highs and higher lows suggest an uptrend; lower highs and lower lows suggest a downtrend. A mixed sequence may be a range or transition.','both'],
 ['Structure can fail','A new low can challenge an uptrend without proving a lasting downtrend. Wait for enough evidence and define where an interpretation would be invalid.','both']],
 [
 ['A swing high is…','A local peak','Every green candle','The chart’s opening price'],['A swing low is…','A local trough','Every red candle','The newest close'],['An uptrend often forms…','Higher highs and higher lows','Only green candles','Equal closes'],['A downtrend often forms…','Lower highs and lower lows','Only long wicks','No pullbacks'],['A mixed swing sequence may suggest…','A range or transition','A certain breakout','Invalid market data'],['Why inspect neighbouring prices?','A swing is relative to its surroundings','It changes the OHLC','It guarantees a reversal'],['Does one lower low prove a lasting downtrend?','No','Yes','Only on a daily chart'],['What is a higher low?','A trough above the previous trough','A high above the previous high','A green candle'],['Which clue challenges an uptrend?','A break below an important prior swing low','Any red candle','A short upper wick'],['What should accompany a structure idea?','A level that would invalidate it','A guaranteed target','Only a colour label']]),
L('Support zones',4,[
 ['Notice where declines paused','Support is an area where previous selling was met by enough buying to pause or reverse a fall. It describes past behaviour, not a fixed floor.','both'],
 ['Mark an area, not a pixel','Turns rarely occur at exactly one price. Mark a narrow zone around repeated reactions and consider the volatility of the market.','both'],
 ['Plan for failure','A support zone can break. A fresh close through it, followed by continued movement, changes the evidence. Consider invalidation before treating the zone as useful.','both']],
 [
 ['Support describes…','An area where declines previously paused','A guaranteed minimum price','An order type'],['Why draw a zone?','Reactions span a range of prices','Exact prices are illegal','Zones cannot break'],['Does prior support guarantee a bounce?','No','Yes','Only with a green candle'],['Repeated tests of a zone provide…','More observed reactions, not certainty','A guaranteed reversal','A fixed profit target'],['What might weaken a support thesis?','Sustained trading below the zone','A small wick above it','A new chart colour'],['Is support based on past or future action?','Past action','Future prices','Broker settings'],['What changes a zone’s useful width?','Typical price variation','The site font','The number of tabs open'],['What is an invalidation point?','Where the trade idea no longer fits','Where profit is guaranteed','The next candle high'],['Can former support become resistance?','Yes, sometimes','Never','Only on one-minute charts'],['Best use of a support zone?','One piece of evidence in a plan','An automatic buy order','Proof of a bottom']]),
L('Resistance zones',4,[
 ['Notice where rises paused','Resistance is an area where prior advances met enough selling to stall. It is evidence of past supply at that area, not a ceiling the market must respect.','both'],
 ['Look for repeated reactions','Several tests can make a zone worth watching. Compare how far price retreated after each test and whether closes begin to hold above it.','both'],
 ['Update when it breaks','If price establishes itself above resistance, the old interpretation needs review. What was resistance may later be tested as support.','both']],
 [
 ['Resistance describes…','An area where rises previously stalled','A guaranteed maximum price','A stop-loss order'],['Is resistance an exact line?','Usually better treated as a zone','Always one exact price','Always the session high'],['What may challenge a resistance idea?','Sustained closes above the zone','One small red candle','A long lower wick far away'],['Do repeated reactions guarantee another rejection?','No','Yes','Only on daily charts'],['What is a retest?','Price returns to a previously important area','Price repeats the same candle exactly','A reset of the app'],['Can broken resistance later act as support?','Yes, sometimes','No','Only with a news event'],['What should you compare at repeated tests?','Reaction strength and closes','The chart background','Only candle count'],['What is resistance based on?','Observed past reactions','Guaranteed future supply','A fixed exchange rule'],['A close above resistance is…','Evidence to reassess the zone','Proof that price cannot fall','The end of all risk'],['Best use of a resistance zone?','Part of a wider decision process','An automatic sell signal','A certain target']]),
L('Breakouts and follow-through',5,[
 ['A breakout changes location','A breakout occurs when price moves beyond a watched range or zone. The move is interesting because it changes the structure traders were using.','both'],
 ['Ask whether price holds','One intraperiod spike may reverse. A close beyond the zone and later trading that holds there provide stronger, though still imperfect, evidence.','both'],
 ['Plan before chasing','A fast move can tempt late entries. Mark the breakout area, likely invalidation and acceptable risk before acting; waiting is a valid choice.','both']],
 [
 ['A breakout is price moving…','Beyond a watched range or zone','Exactly to its prior close','Only within a range'],['Is a wick through a zone always a breakout?','No','Yes','Only if red'],['What strengthens breakout evidence?','Closing and holding beyond the zone','A taller screen','One isolated spike'],['What is follow-through?','Continued action in the breakout direction','A colour change','The size of the toolbar'],['Can a breakout fail?','Yes','No','Only in synthetic charts'],['Why can chasing be risky?','Entry may be far from invalidation','It always loses','It removes price data'],['What should be marked before action?','Invalidation and risk','A guaranteed target','A lucky candle'],['Can waiting after a breakout be reasonable?','Yes','No','Only for beginners'],['What may a retest show?','Whether the old zone holds from the other side','An exact future outcome','Missing OHLC'],['Which is evidence, not certainty?','A close beyond resistance','A guaranteed upward move','A promise of profit']]),
L('False breaks and traps',5,[
 ['Price can return inside','A false break pushes beyond a level, then returns to the prior range. The initial move attracted attention, but did not hold.','both'],
 ['Compare closes with wicks','A wick outside a zone and a close back inside can be a useful warning. Even a close outside can fail later, so avoid treating one candle as final proof.','both'],
 ['Use the failed level','After the move returns inside, the failed edge becomes a reference for invalidation and review. Focus on what changed in the evidence rather than feeling obliged to reverse.','both']],
 [
 ['A false break moves beyond a level then…','Returns inside the prior area','Continues forever','Deletes earlier candles'],['What can a wick beyond resistance followed by a close inside suggest?','The move did not hold through that close','Guaranteed reversal','Missing volume'],['Can a close outside later fail?','Yes','No','Only on a daily chart'],['Why avoid acting on one spike?','It may not hold','Spikes have no high price','All spikes are fake'],['What becomes a useful reference after a failed break?','The failed range edge','The site logo','The candle count alone'],['Does a false break require immediate reversal trading?','No','Yes','Only when green'],['What is the prior range?','The area price traded before the break','The next day’s high','The broker spread'],['What should be reassessed after price returns inside?','The original breakout idea','The colour theme','The OHLC definition'],['Can false breaks occur at support?','Yes','No','Only at resistance'],['What is the best response to conflicting evidence?','Pause and update the plan','Ignore the close','Assume the first idea must win']]),
L('Volume: participation',5,[
 ['Volume counts activity','Volume measures units traded over a period. On many markets, a volume bar beneath a candle shows how much activity accompanied that price movement.','both'],
 ['Compare like with like','High volume relative to recent periods can show unusual participation. It does not tell you that buyers or sellers will win next; every completed trade has both sides.','both'],
 ['Know the data source','Some forex charts show tick volume, a count of price updates rather than consolidated traded units. Check what your platform reports before comparing markets.','both']],
 [
 ['Volume measures…','Trading activity during a period','The next price','The body height'],['High volume relative to recent bars indicates…','Unusually high participation','Guaranteed continuation','Only buying'],['Does every trade have a buyer and seller?','Yes','No','Only in equities'],['Can volume alone predict direction?','No','Yes','Only when it doubles'],['Where are volume bars commonly shown?','Beneath the price chart','Inside the account menu','At the wick tip'],['What is tick volume?','A count of price updates','All traded units globally','The distance between open and close'],['Why check the data source?','Volume definitions differ by market and feed','It changes candle colour','It guarantees accuracy'],['What is a sensible comparison?','Current volume versus recent similar periods','Today’s volume versus font size','Only green bars'],['Can a high-volume candle have a small body?','Yes','No','Only in forex'],['How should volume be used?','As context alongside price structure','As a guaranteed signal','As a substitute for risk planning']]),
L('Volatility and range',5,[
 ['Movement has a typical size','Volatility describes how much price varies. A market with wide recent candles and ranges needs different expectations from a quiet one.','both'],
 ['Measure what is visible','A candle’s high-to-low range shows that period’s span. Compare several periods, since a single large candle can be unusual rather than typical.','both'],
 ['Risk must fit movement','A stop placed inside ordinary price noise may be reached without disproving the idea. Wider stops usually require smaller position sizes for the same planned risk.','both']],
 [
 ['Volatility describes…','How much price varies','Guaranteed direction','Trading hours only'],['Candle range is…','High minus low','Close minus open only','Volume divided by price'],['Why compare several candles?','To estimate typical movement','To guarantee a reversal','To hide outliers'],['A wide candle is always typical?','No','Yes','Only if red'],['A stop inside normal noise may…','Be hit without disproving the idea','Always protect profit','Never trigger'],['If a stop must be wider for the same monetary risk, size should…','Usually be smaller','Always be larger','Stay fixed regardless'],['Can volatility change over time?','Yes','No','Only at year end'],['Does high volatility imply an uptrend?','No','Yes','Only on daily charts'],['What does a quiet market often show?','Smaller recent ranges','Guaranteed safety','No risk'],['Which is a better risk reference?','Observed movement plus an invalidation level','An arbitrary fixed distance','The colour of the last candle']]),
L('Orders and execution',5,[
 ['Market versus limit','A market order seeks immediate execution at available prices. A limit order sets the worst acceptable price but may not fill. Both involve execution uncertainty.','both'],
 ['Stops are triggers','A stop order activates when its trigger price is reached. In a fast market, the eventual fill may differ from the trigger; this is slippage.','both'],
 ['Costs matter','The bid-ask spread and fees affect results. Include them in any simulation or plan, especially when a target is close to the entry.','both']],
 [
 ['A market order prioritises…','Speed of execution','An exact guaranteed price','No transaction costs'],['A limit order sets…','A price boundary','A guaranteed fill','A stop distance'],['Can a limit order remain unfilled?','Yes','No','Only when bearish'],['A stop order activates when…','Its trigger is reached','The user earns XP','Volume disappears'],['What is slippage?','A fill different from the expected trigger price','A longer wick','An account password error'],['What is the spread?','Difference between bid and ask','High minus low','Daily profit'],['Can fees change a small trade’s outcome?','Yes','No','Only on monthly charts'],['Does a stop price guarantee that exact fill?','No','Yes','Only for buys'],['What should a simulation include?','Spread, fees and realistic fills','Only the last close','Guaranteed best price'],['Which order can control price but not guarantee execution?','Limit order','Market order','Every order equally']]),
L('Risk before reward',5,[
 ['Decide where the idea fails','An invalidation level is where your original reason for a trade no longer holds. A stop can express that level, but stops can fill at different prices in fast markets.','both'],
 ['Set an amount you can tolerate','Choose a monetary risk budget before considering position size. Educational examples may use a percentage of a simulated account, but the right limit depends on the person and setting.','both'],
 ['Separate process from outcome','A planned trade can lose; an unplanned one can win. Evaluate whether the entry, invalidation and size made sense using information available at the time.','both']],
 [
 ['An invalidation level marks…','Where the original idea no longer fits','A guaranteed profit point','The next candle open'],['Risk should be considered…','Before entering','Only after a loss','Only when trading ends'],['Can a planned trade lose?','Yes','No','Only if bearish'],['Can a poor decision make money?','Yes','No','Only in simulations'],['A stop may fill beyond its trigger because of…','Slippage','A red label','The lesson order'],['A risk budget is…','The amount set aside as acceptable potential loss','Guaranteed maximum profit','The full account balance'],['Which is a process measure?','Was invalidation defined in advance?','Did the last candle turn green?','Was the outcome lucky?'],['Does a good outcome prove a good plan?','No','Yes','Only with high volume'],['What belongs in a pre-entry plan?','Entry, invalidation and size','Only a target','Only a colour signal'],['What should a loss trigger in review?','Check reasoning and execution','Assume the idea was always foolish','Double size automatically']]),
L('Position sizing',5,[
 ['Start with risk money','Position size connects your planned loss per unit with your total risk budget. A common basic calculation is risk budget divided by entry-to-stop distance per unit.','both'],
 ['Work through an example','If simulated risk is £50 and entry-to-stop distance is £2 per unit, the simple size is 25 units before costs and contract details.','both'],
 ['Account for the instrument','Contracts can have multipliers, minimum sizes, fees and slippage. Check the instrument’s rules; a simple share calculation does not always transfer directly.','both']],
 [
 ['Basic position size equals…','Risk budget divided by risk per unit','Risk budget times entry price','Profit target divided by volume'],['£50 risk and £2 per unit implies…','25 units','100 units','2 units'],['If stop distance doubles and budget stays fixed, size should…','Halve','Double','Stay the same'],['What is risk per unit?','Entry-to-invalidation distance adjusted for contract value','Account password length','The previous candle body'],['Why consider contract multipliers?','They change money risk per price unit','They change candle colour','They guarantee liquidity'],['Do fees affect the risk calculation?','Yes','No','Only for short trades'],['A fixed position size with a wider stop risks…','More money','Less money','Exactly the same'],['Should size be calculated before entry?','Yes','No','Only after profit'],['Can minimum lot sizes prevent an exact planned size?','Yes','No','Only on charts without volume'],['What is the safer response if the minimum size exceeds your risk limit?','Skip or find a suitable instrument','Raise the risk limit automatically','Ignore the stop']]),
L('Reward-to-risk ratios',5,[
 ['Compare potential distances','The reward-to-risk ratio compares the planned target distance with the entry-to-invalidation distance. A target £4 away and stop £2 away gives 2:1 before costs.','both'],
 ['A ratio is not a probability','A large target may be less likely to be reached. The ratio alone cannot tell whether a strategy has positive expectancy.','both'],
 ['Keep the target plausible','Place targets with reference to structure or a tested plan. Moving a target farther away merely to improve a ratio does not improve the trade itself.','both']],
 [
 ['A £4 target and £2 stop gives…','2:1 reward to risk','1:2 reward to risk','4:1 reward to risk'],['The ratio compares…','Planned reward distance with risk distance','Volume with volatility','Green candles with red'],['Does a 3:1 target guarantee profit?','No','Yes','Only with a stop'],['Why might a distant target be less useful?','It may be less likely to be reached','It changes the open','It removes costs'],['Should a target be moved only to improve the ratio?','No','Yes','Only after entry'],['What can influence target placement?','Nearby structure and tested rules','Only the desired ratio','The site accent colour'],['Are costs part of practical reward-to-risk?','Yes','No','Only if the trade loses'],['If risk distance doubles while target stays fixed, ratio…','Falls','Rises','Stays equal'],['Can a smaller ratio still be viable?','Possibly, depending on outcomes and costs','Never','Only with no stop'],['What else is needed beyond a ratio?','Outcome frequencies and consistent execution','A brighter chart','A guaranteed forecast']]),
L('Build a trading plan',5,[
 ['Write the setup before action','A plan describes the conditions for a possible trade: market context, trigger, invalidation, size and exit. This makes a decision reviewable.','both'],
 ['Include the no-trade case','List conditions under which you will stand aside, such as unclear structure or unacceptable risk. Not every chart offers an opportunity.','both'],
 ['Make rules observable','“Only when the trend feels good” is hard to test. “After a higher low and close above the prior swing high” is more specific, although never a guarantee.','both']],
 [
 ['A plan should include…','Setup, trigger, invalidation, size and exit','Only a hoped-for target','Only market colour'],['Why write rules before action?','To make decisions reviewable','To guarantee profit','To avoid all losses'],['Is no trade a valid planned outcome?','Yes','No','Only in a downtrend'],['What makes a rule testable?','Observable conditions','Vague confidence','A lucky result'],['Which rule is more precise?','Close above a named swing high','Trade when it feels right','Buy all green candles'],['What might block a trade?','Risk exceeding the preset limit','The chart being dark green','Having finished a lesson'],['Should a plan be revised using evidence?','Yes','Never','Only after wins'],['What is an entry trigger?','A specified condition for acting','A guaranteed fill','A level of XP'],['How does an exit rule help?','It defines how to respond after entry','It predicts every move','It removes fees'],['What is useful when reviewing a plan?','Compare actual decisions with written rules','Judge by profit alone','Change the rule after every candle']]),
L('Review and journal',4,[
 ['Capture the decision','A simple journal records chart context, planned entry, invalidation, size, outcome and what you saw before the trade. A screenshot may help preserve the original view.','both'],
 ['Tag repeated patterns','Use a small set of tags such as trend, range, breakout or rule violation. After enough examples, patterns in your decisions become easier to spot.','both'],
 ['Review process honestly','Look for repeated mistakes and strong habits. Judge an action by the information available at decision time, then use the outcome to improve the process.','both']],
 [
 ['What should a journal capture?','The setup and decision as they appeared then','Only winning trades','Only final balance'],['Why preserve the original chart view?','To review what was knowable at the time','To predict the future','To remove fees'],['Which is a useful tag?','Breakout','Lucky day only','Perfect outcome'],['When should an entry reason be recorded?','Before or at the decision','Only after seeing the result','Only at month end'],['Should losing trades be journalled?','Yes','No','Only large ones'],['What can repeated tags reveal?','Patterns in decisions and results','Guaranteed future profits','A new OHLC value'],['What is hindsight bias?','Treating an outcome as obvious after it happens','Recording a stop beforehand','Using a timeframe'],['What is a process question?','Did I follow my stated rule?','Was my candle green?','Did I get lucky?'],['Why review a batch of decisions?','Repeated patterns are clearer than one outcome','One result is always enough','It removes uncertainty'],['What is a useful next step after spotting a recurring mistake?','Change one specific rule or habit and track it','Double every position','Delete the losing records']]),
L('Biases and patience',5,[
 ['Notice urgency','Fear of missing out can make a late entry feel necessary. The market offers many future setups; missing one move is usually less harmful than abandoning a plan.','both'],
 ['Separate belief from evidence','Confirmation bias makes supportive candles feel more important than contradictory ones. Before acting, ask what would prove the idea wrong.','both'],
 ['Protect the pause','After a loss or win, emotion can influence the next size or entry. A short pause and a written checklist can keep the next decision anchored to the plan.','both']],
 [
 ['FOMO stands for…','Fear of missing out','Forecast of market orders','Frequency of moving opens'],['What can FOMO encourage?','A late unplanned entry','A guaranteed better price','A lower spread'],['Confirmation bias favours…','Evidence that supports an existing belief','All evidence equally','Only volume data'],['What question challenges confirmation bias?','What would prove my idea wrong?','How can I ignore the stop?','Why must I be right?'],['Is missing one move the same as losing money?','No','Yes','Only in a downtrend'],['After a loss, what can help?','Pause and check the written plan','Double size automatically','Chase the next candle'],['After a win, can overconfidence appear?','Yes','No','Only with leverage'],['What is a checklist for?','Consistent decision steps','Guaranteed outcomes','Changing the chart colour'],['When is no trade a strong decision?','When the setup or risk does not fit the plan','Never','Only after three red candles'],['How can patience be assessed?','Record whether you followed your conditions','Count only wins','Ignore skipped trades']])
];

export function publicLessons(){return lessons.map(({title,minutes,slides,questions})=>({title,minutes,slides,questions:questions.map(([prompt,correct,wrongA,wrongB],index)=>({prompt,options:[correct,wrongA,wrongB].map((_,i)=>[correct,wrongA,wrongB][(i+index)%3])}))}));}
export function correctIndex(lessonIndex,questionIndex){return (3-questionIndex%3)%3;}
